#!/usr/bin/env sh
# Writes the Homebrew formula for one release to stdout.
#
#   scripts/formula.sh 0.2.1 dir-with-the-release-.sha256-files > Formula/background-remover.rb
#
# The formula installs the prebuilt binaries from the GitHub release, so the
# tap never compiles anything. release.yml runs this after the binaries are
# up and pushes the result to daniel-oh/homebrew-tap.
set -eu
VERSION=$1
SUMS=$2
BASE="https://github.com/daniel-oh/background-remover/releases/download/v$VERSION"

sum() { # target
  f="$SUMS/background-remover-v$VERSION-$1.tar.gz.sha256"
  [ -f "$f" ] || { echo "formula: missing $f" >&2; exit 1; }
  cut -d' ' -f1 "$f"
}
MAC_ARM=$(sum aarch64-apple-darwin)
LINUX_ARM=$(sum aarch64-unknown-linux-gnu)
LINUX_X86=$(sum x86_64-unknown-linux-gnu)

cat <<RUBY
# Generated by scripts/formula.sh in daniel-oh/background-remover for v$VERSION.
class BackgroundRemover < Formula
  desc "Background removal as a small HTTP service"
  homepage "https://github.com/daniel-oh/background-remover"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "$BASE/background-remover-v$VERSION-aarch64-apple-darwin.tar.gz"
      sha256 "$MAC_ARM"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/background-remover-v$VERSION-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$LINUX_ARM"
    end
    on_intel do
      url "$BASE/background-remover-v$VERSION-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$LINUX_X86"
    end
  end

  def install
    bin.install "background-remover"
  end

  def caveats
    <<~EOS
      The model (178 MB) is not bundled. Fetch it once:
        mkdir -p #{var}/background-remover
        curl -L -o #{var}/background-remover/isnet-general-use.onnx \\\\
          https://github.com/danielgatis/rembg/releases/download/v0.0.0/isnet-general-use.onnx
      Then either run it in the foreground:
        MODEL_PATH=#{var}/background-remover/isnet-general-use.onnx background-remover
      or as a service on 127.0.0.1:7000, which uses that path:
        brew services start background-remover
    EOS
  end

  service do
    run [opt_bin/"background-remover"]
    environment_variables MODEL_PATH: var/"background-remover/isnet-general-use.onnx",
                          BIND:       "127.0.0.1"
    keep_alive true
    log_path var/"log/background-remover.log"
    error_log_path var/"log/background-remover.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/background-remover --version")
  end
end
RUBY
